# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170421_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eating', models.BigIntegerField(null=True)),
                ('drinking', models.BigIntegerField(null=True)),
                ('toileting', models.BigIntegerField(null=True)),
                ('showering', models.BigIntegerField(null=True)),
                ('leaving', models.BigIntegerField(null=True)),
                ('sleeping', models.BigIntegerField(null=True)),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
    ]
